spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-9pn-820c.us.auth0.com/.well-known/jwks.json