eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
spring:

  application:
    name: msvc-orders

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=quack_store;encrypt=false;trustServerCertificate=true
    username: sa
    password: mares123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL
openapi:
  service:
    title: Orders doc
    version: 1.0.0
    url-gateway: http://localhost:8080
    url-inventory: http://localhost:8082
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /api/orders/v3/api-docs

feign:
  client:
    config:
      inventory-service:
        connectTimeout: 10000
        readTimeout: 60000
        loggerLevel: full
        decode404: false
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true